apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hpp-api-monitor
  namespace: hpp
  labels:
    release: prom
    app: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  endpoints:
    - port: "http"
      path: /metrics
      interval: 15s
      scheme: http
  namespaceSelector:
    matchNames:
      - hpp